### ISSUE TITLE
Testing Issue(negative integer)

### ISSUE THREAD

**Issue by colbyschulz** [learn-co-curriculum/prime-ruby#10]
I may be missing something, but it appears prime_spec.rb from the Implementing Prime lab only checks for false returns for 0,1,4,40, and 101013. No negative integers are being tested!

I only came to this conclusion after helping someone else with the lab and noticing they took that specific situation into account.  My original code didn't take negatives into account but still passed all tests(It was an easy fix, and I submitted an update). 

Others may also have code that passed rspec tests but doesn't truly check for prime numbers!

Figured it might be worth looking at. 

Thanks,

-Colby

**Comment by AnnJohn** [comment]
thanks for raising the issue @colbyschulz 

@mendelB, can you review this? If you think it's easier to add a note saying that negative numbers won't be tested here, that's fine too. Thanks,
