### ISSUE TITLE
will not fork lab with open button

### ISSUE THREAD

**Issue by amjack59** [learn-co-curriculum/prime-ruby#12]
just hit open to start lab and learn ide popped up but does not show that lab has been forked and when  I submitted lab via learn submit it is not showing that it has been pushed and lab completed.

**Comment by AnnJohn** [comment]
hi @amjack59 sorry for the delay with this. This is a product problem so could you please file a bug report? If you click on your profile pic in Learn, you'll see a dropdown menu with an option to report a bug. 

Also you can use the Ask a Question tool to get one-on-one support as well. Thanks!
