### ISSUE TITLE
Suggest a simpler solution

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/prime-ruby#13]
Suggest having a solution that's more aligned with what Learners should know at this point in the curriculum. Something like this:

``` ruby
def prime?(n)
  n == 0 || n == 1 ? false : (2..n-1).to_a.all?{|d| n % d != 0}
end
```

**Comment by itzsaga** [comment]
This solution branch is confusing to students as it solves problems that they're not required to solve.

**Comment by sgharms** [comment]
Thanks for your suggestion. Implemented!
