### ISSUE TITLE
`2` needs to be checked. 

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/prime-ruby#16]
2 is the only even prime and is sometimes overlooked. Certain implementations will also start with a base divisor of 3 in order to increment by 2 and skip over even numbers; some students seem to be forgetting about two as a prime. 

I also agree with the other open issue; the solution is not only quite confusing, but a somewhat odd and extremely slow implementation of the sieve of eratosthenes that actually ends up being slower than n/2 due to the overhead before it actually calculates. (This could be ameliorated with memoization, or a different implementation, or both.)

**Comment by sgharms** [comment]
Agree, will change the implementation. Also we have added a test for 2. Thanks for the help.
