### ISSUE TITLE
Enumerators - Order in Curriculum

### ISSUE THREAD

**Issue by baintonw** [learn-co-curriculum/prime-ruby#20]
This might sound like a strange complaint, but it seems like this "Introduction to Enumerators" chapter would have been incredibly useful far earlier in the curriculum, perhaps during the Arrays section. We've been using '.each' fairly extensively already, and to have this incredibly useful definition of what '.each' and '.collect' do right after, say, the "badges" lab seems to be putting the cart before the horse.

**Comment by drakeltheryuujin** [comment]
Hi @baintonw,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
